# Generated by Django 5.1.4 on 2025-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Критерии оценки товара (качество, цена, упаковка, эффективность и т.д.)', verbose_name='Атрибуты оценки'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_explanation',
            field=models.TextField(blank=True, help_text='Почему пользователь поставил такую оценку', null=True, verbose_name='Объяснение оценки'),
        ),
    ]
