"""
Настройки Django проекта Pearl.

Этот файл содержит все настройки конфигурации Django приложения:
- Безопасность и секретные ключи
- База данных (PostgreSQL)
- Установленные приложения
- Middleware
- REST Framework и JWT аутентификация
- CORS настройки
- Медиа и статические файлы

ВАЖНО: Для production необходимо изменить:
- SECRET_KEY на безопасный ключ
- DEBUG = False
- ALLOWED_HOSTS на конкретные домены
- CORS настройки для безопасности

Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path

# ==================== Базовые пути ====================
# Корневая директория проекта (папка, содержащая manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# ==================== Безопасность ====================
# ВАЖНО: Эти настройки подходят только для разработки!
# Для production необходимо изменить все значения ниже

# Секретный ключ для криптографической подписи
# ВАЖНО: В production должен быть уникальным и храниться в переменных окружения!
SECRET_KEY = 'django-insecure-e8znb28rarf9e2%w7mee&5c@-3azzfc-w12#d(u4by)7g1a3)6'

# Режим отладки (показывает детальные ошибки)
# ВАЖНО: В production должно быть False!
DEBUG = True

# Разрешенные хосты для доступа к серверу
# ['*'] разрешает доступ с любых хостов (только для разработки!)
# В production указать конкретные домены: ['example.com', 'www.example.com']
ALLOWED_HOSTS = ['*']  # Для локальной разработки


# ==================== Установленные приложения ====================

INSTALLED_APPS = [
    # Стандартные приложения Django
    'django.contrib.admin',          # Административная панель
    'django.contrib.auth',           # Система аутентификации
    'django.contrib.contenttypes',   # Система типов контента
    'django.contrib.sessions',       # Управление сессиями
    'django.contrib.messages',       # Система сообщений
    'django.contrib.staticfiles',    # Управление статическими файлами

    # Сторонние библиотеки
    'rest_framework',                # Django REST Framework для API
    'corsheaders',                   # CORS заголовки для кросс-доменных запросов

    # Приложения проекта
    'user',      # Управление пользователями (регистрация, вход, профиль)
    'products',  # Управление товарами (каталог, категории)
    'orders',    # Управление заказами
    'reviews',   # Управление отзывами о товарах
]

# ==================== Middleware (промежуточное ПО) ====================
# Middleware обрабатывает запросы и ответы в определенном порядке

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',      # Безопасность (HTTPS, заголовки)
    'corsheaders.middleware.CorsMiddleware',              # CORS заголовки (должен быть рано)
    'django.contrib.sessions.middleware.SessionMiddleware', # Управление сессиями
    'django.middleware.common.CommonMiddleware',           # Общие функции (нормализация URL)
    'django.middleware.csrf.CsrfViewMiddleware',          # Защита от CSRF атак
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Аутентификация пользователей
    'django.contrib.messages.middleware.MessageMiddleware',    # Система сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Защита от clickjacking
]

# Главный файл URL маршрутизации
ROOT_URLCONF = 'config.urls'

# ==================== Настройки шаблонов ====================
# Используется для административной панели Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI приложение для развертывания на сервере
WSGI_APPLICATION = 'config.wsgi.application'


# ==================== Настройки базы данных ====================
# Используется PostgreSQL для хранения данных

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # Драйвер PostgreSQL
        'NAME': 'pearl',          # Имя базы данных
        'USER': 'postgres',       # Пользователь базы данных
        'PASSWORD': '12345',      # Пароль (в production хранить в переменных окружения!)
        'HOST': '127.0.0.1',      # Адрес сервера БД (localhost)
        'PORT': 5432,             # Порт PostgreSQL
    }
}


# ==================== Валидация паролей ====================
# Правила для проверки надежности паролей при регистрации

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Проверяет, что пароль не похож на имя пользователя, email и т.д.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Проверяет минимальную длину пароля (по умолчанию 8 символов)
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Проверяет, что пароль не входит в список распространенных паролей
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Проверяет, что пароль не состоит только из цифр
    },
]


# ==================== Интернационализация ====================

LANGUAGE_CODE = 'en-us'  # Язык по умолчанию
TIME_ZONE = 'UTC'        # Часовой пояс
USE_I18N = True          # Включить интернационализацию
USE_TZ = True            # Использовать часовые пояса


# ==================== Статические и медиа файлы ====================

# URL для статических файлов (CSS, JavaScript)
STATIC_URL = 'static/'
# Директория для сбора статических файлов при развертывании
STATIC_ROOT = BASE_DIR / 'staticfiles'

# URL для медиа файлов (загруженные пользователями изображения товаров)
MEDIA_URL = '/media/'
# Директория для хранения медиа файлов
MEDIA_ROOT = BASE_DIR / 'media'

# Тип поля для автоматических первичных ключей
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Кастомная модель пользователя (вместо стандартной Django User)
AUTH_USER_MODEL = 'user.User'

# ==================== CORS настройки ====================
# CORS (Cross-Origin Resource Sharing) позволяет браузеру делать запросы
# с одного домена на другой (необходимо для Android приложения)

# ВАЖНО: Для production изменить на False и указать конкретные домены!
CORS_ALLOW_ALL_ORIGINS = True  # Для разработки разрешает все источники

# Список разрешенных источников (используется если CORS_ALLOW_ALL_ORIGINS = False)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# ==================== Настройки Django REST Framework ====================
# Конфигурация для работы с API

REST_FRAMEWORK = {
    # Классы разрешений по умолчанию
    # AllowAny - разрешает доступ всем (в production изменить на IsAuthenticated!)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Классы аутентификации
    # JWTAuthentication - аутентификация через JWT токены
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Пагинация (разбиение на страницы)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20  # Количество элементов на странице
}

# ==================== Настройки JWT (JSON Web Tokens) ====================
# JWT используется для аутентификации пользователей в API
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),      # Время жизни access токена (1 день)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Время жизни refresh токена (7 дней)
    'ROTATE_REFRESH_TOKENS': True,                   # Обновлять refresh токен при каждом использовании
    'BLACKLIST_AFTER_ROTATION': True,                # Добавлять старые токены в черный список
    'AUTH_HEADER_TYPES': ('Bearer',),                # Тип заголовка авторизации
}