# Generated by Django 5.1.4 on 2025-11-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_verified_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('DRY', 'Сухая'), ('OILY', 'Жирная'), ('COMBINATION', 'Комбинированная'), ('NORMAL', 'Нормальная'), ('SENSITIVE', 'Чувствительная')], max_length=20, verbose_name='Тип кожи')),
                ('primary_need', models.CharField(choices=[('HYDRATION', 'Увлажнение'), ('NUTRITION', 'Питание'), ('PROTECTION', 'Защита'), ('REGENERATION', 'Регенерация'), ('MATTIFICATION', 'Матирование'), ('SOOTHING', 'Успокоение')], max_length=20, verbose_name='Основная потребность')),
                ('secondary_needs', models.JSONField(default=list, verbose_name='Вторичные потребности')),
                ('concerns', models.JSONField(default=list, verbose_name='Проблемы кожи')),
                ('age_group', models.CharField(choices=[('YOUNG', '18-25'), ('ADULT', '26-35'), ('MATURE', '36-45'), ('SENIOR', '45+')], max_length=20, verbose_name='Возрастная группа')),
                ('test_answers', models.JSONField(default=dict, verbose_name='Ответы на вопросы теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест кожи',
                'verbose_name_plural': 'Тесты кожи',
                'ordering': ['-created_at'],
            },
        ),
    ]
