# Generated by Django 5.1.4 on 2025-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_skintest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Может содержать буквы, цифры, пробелы и специальные символы', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
