# Generated by Django 5.1.4 on 2025-11-25 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
                ('total_earned', models.IntegerField(default=0, verbose_name='Всего заработано')),
                ('total_spent', models.IntegerField(default=0, verbose_name='Всего потрачено')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бонусная карта',
                'verbose_name_plural': 'Бонусные карты',
            },
        ),
    ]
