# Generated by Django 5.1.4 on 2025-11-27 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_bonuscard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skintest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест типа кожи', 'verbose_name_plural': 'Тесты типа кожи'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Код верификации', 'verbose_name_plural': 'Коды верификации'},
        ),
        migrations.RemoveField(
            model_name='skintest',
            name='secondary_needs',
        ),
        migrations.RemoveField(
            model_name='skintest',
            name='test_answers',
        ),
        migrations.AddField(
            model_name='bonuscard',
            name='level',
            field=models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platinum', 'Платина')], default='bronze', max_length=20, verbose_name='Уровень карты'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='total_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего заработано'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='total_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего потрачено'),
        ),
        migrations.AlterField(
            model_name='skintest',
            name='age_group',
            field=models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('45+', '45+')], max_length=10, verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='skintest',
            name='concerns',
            field=models.JSONField(blank=True, default=list, help_text='Список проблем кожи (акне, морщины, пигментация и т.д.)', verbose_name='Проблемы'),
        ),
        migrations.AlterField(
            model_name='skintest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='skintest',
            name='primary_need',
            field=models.CharField(choices=[('hydration', 'Увлажнение'), ('nutrition', 'Питание'), ('protection', 'Защита'), ('regeneration', 'Регенерация'), ('mattification', 'Матирование'), ('soothing', 'Успокоение')], max_length=20, verbose_name='Основная потребность'),
        ),
        migrations.AlterField(
            model_name='skintest',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'Сухая'), ('oily', 'Жирная'), ('combination', 'Комбинированная'), ('normal', 'Нормальная'), ('sensitive', 'Чувствительная')], max_length=20, verbose_name='Тип кожи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации пользователя', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения пользователя (опционально)', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Подтвержден ли пользователь (через SMS код)', verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Номер телефона в формате +7XXXXXXXXXX (используется для входа)', max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления данных пользователя', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Полный адрес пользователя', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Фото профиля пользователя', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая информация о пользователе', max_length=500, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Город проживания', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Страна проживания', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, help_text='Подписан ли пользователь на email рассылку', verbose_name='Подписка на рассылку'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Почтовый индекс для доставки', max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Предпочтения пользователя (любимые категории, бренды и т.д.)', verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Связанный пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код верификации'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('earned', 'Начислено'), ('spent', 'Потрачено')], max_length=10, verbose_name='Тип транзакции')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.bonuscard', verbose_name='Бонусная карта')),
            ],
            options={
                'verbose_name': 'Транзакция по бонусной карте',
                'verbose_name_plural': 'Транзакции по бонусным картам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок рассылки', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Текст рассылки', verbose_name='Содержание')),
                ('subject', models.CharField(help_text='Тема email письма', max_length=200, verbose_name='Тема письма')),
                ('target_audience', models.CharField(choices=[('all', 'Все пользователи'), ('subscribed', 'Только подписанные'), ('custom', 'Выборочно')], default='subscribed', max_length=50, verbose_name='Целевая аудитория')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Дата и время отправки рассылки', null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Дата и время фактической отправки', null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(help_text='Администратор, создавший рассылку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
