# Generated by Django 5.1.4 on 2025-11-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_points_earned',
            field=models.IntegerField(default=0, verbose_name='Начислено бонусных баллов'),
        ),
        migrations.AddField(
            model_name='order',
            name='bonus_points_used',
            field=models.IntegerField(default=0, verbose_name='Использовано бонусных баллов'),
        ),
    ]
