# Generated by Django 5.1.4 on 2025-11-27 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_colors_product_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории, отображаемое в каталоге', max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL (например, "makeup", "skin-care")', max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории для пользователей', null=True, verbose_name='Описание категории')),
                ('icon', models.CharField(blank=True, help_text='Название иконки для отображения в приложении', max_length=50, null=True, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли категорию в каталоге', verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, help_text='Порядок отображения категории в списке (меньше = выше)', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(help_text='Уникальный артикул товара для идентификации', max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text="Название бренда производителя (например, L'Oreal, Maybelline)", max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Makeup', 'Макияж'), ('Skin care', 'Уход за кожей'), ('Hair care', 'Уход за волосами'), ('Manicure and pedicure', 'Маникюр и педикюр'), ('Accessories', 'Аксессуары'), ('Perfumery', 'Парфюмерия'), ('Other', 'Другое')], default='Other', help_text='Категория товара для организации каталога', max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='Доступные цвета товара (например: ["Белый", "Розовый"])', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Подробное описание товара, его свойств и применения', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Список особенностей товара (например: ["Увлажнение", "SPF 50"])', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение товара (загружается в media/products/)', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Можно ли заказать этот товар (влияет на отображение в каталоге)', verbose_name='Доступен для заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Название товара, отображаемое в каталоге', max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Исходная цена до скидки (для отображения перечеркнутой цены)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Старая цена (для скидок)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Текущая цена товара в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='Доступные размеры товара (например: ["50ml", "100ml"])', verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Количество единиц товара на складе', verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес товара в граммах (для расчета доставки)', max_digits=8, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Связь с моделью Category для расширенного управления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория (новая)'),
        ),
    ]
